#!/bin/bash

set -e

systemctl disable --now jupiter-biosupdate.service || echo "jupiter-biosupdate service could not be disabled"
systemctl disable --now jupiter-controller-update.service || echo "jupiter-controller-update service could not be disabled"
systemctl disable --now jupiter-fan-control.service || echo "jupiter-fan-control service could not be disabled"
systemctl --global disable --now sdgyrodsu.service  || echo "sdgyrodsu service could not be disabled"
systemctl disable --now sdgyrodsu.service || echo "sdgyrodsu service could not be disabled"
systemctl --global disable --now jupiter-controller-update.service || echo "jupiter-controller-updatel service could not be disabled"
systemctl --global disable --now jupiter-fan-control.service || echo "jupiter-fan-control service could not be disabled"